### PR TITLE
named fields + fixed some jsons

### PR DESCRIPTION
**Pull request by d3death**

### CODE REVIEW

**Comment by clugh** [comment]
@xyzwarrior What is the purpose of [this commit](https://github.com/clugh/coc-messages/pull/6/commits/524ad83f71d21d7d4db04f8c9482db277d7e019e)?  What happens when a user is in a league, but not a clan?

I'll try to test the everything and get it merged in the morning.

**Comment by d3death** [comment]
alright, let me know if i can help.

**Comment by d3death** [comment]
i also added win streak fix. not sure if i'd have to issue new pull request or this will work

**Comment by clugh** [comment]
Just to follow up, I should have some time to review everything on Sunday, and yes, your updates appear in the pull request, so no need to issue a new one.

**Comment by clugh** [comment]
I cherry-picked some commits and amended a few of them.  Let me know if I missed anything or if you need any help fixing your repos, since I rewrote history a bit.

**Pull request closed without merging**
